name: Benchmark

on:
  push:
    branches:
      - master

jobs:

  test:
    strategy:
      matrix:
        node-version: [ 16, 18, 20 ]

    name: Node ${{ matrix.node-version }}

    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v2

      - name: node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: downloading hyperfine
        run: wget https://github.com/sharkdp/hyperfine/releases/download/v1.16.1/hyperfine_1.16.1_amd64.deb

      - name: installing hyperfine
        run: sudo dpkg -i hyperfine_1.16.1_amd64.deb

      - name: installing dependencies
        run: npm ci

      - name: running benchmark
        shell: bash
        run: bash benchmark.sh
