name: Benchmark

on:
  push:
    branches:
      - master

jobs:

  test:
    strategy:
      matrix:
        node-version: [ 14, 16, 18, 20 ]

    name: Node ${{ matrix.node-version }}

    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v2

      - name: node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: installing
        run: npm ci

      - name: running
        run: npm start
